### ISSUE TITLE
Hi there! Question about this resource!

### ISSUE THREAD

**Issue by lwasser** [geocompx/geocompy#105]
Hi there! 👋 
I am just saying hello. I came across this resource and wondered what direction it was going and whether you wanted some help with it.

In my previous position i worked on a few textbooks - the second of which [had a lot of spatial data processing in python content](earthdatascience.org/courses/use-data-open-source-python/intro-vector-data-python/spatial-data-vector-shapefiles/). It had some other things as well however as it was geared towards earth and environmental data science so some was non spatial. And I moved everything away from rasterio in favor of rioxarray / xarray 2 years ago so that diverges from what is in this book.

But I wondered if you wanted help pulling content together and/or if i could support in some way? I no longer work on the earthdatascience.org website and would love to stay involved with spatial data processing. i'm motivated to contribute to a community resource rather than one i might leave due to a job change and then it becomes unmaintained. 

All the best

**Comment by Robinlovelace** [comment]
Hi Leah, great to hear from you and thanks for getting in touch. Plan is to put together an introductory but comprehensive-of-the-basics open source and open text book, like Geocomputation with R, but for Python, and shorter. Your experience of rioxarray / xarray sounds super relevant here: a key future of the book is planned to be its roughly equal coverage of vector and raster data, Michael is probably best placed to comment on use of rasterio vs those options though. Interested to hear why you moved away from rasterio, for good reason I imagine!

**Comment by michaeldorman** [comment]
Hi Leah, 

Great to hear from you, the resources that you worked on are excellent! 

I'm also very interested to learn from you experience on why you moved from `rasterio` to `rioxarray`. Admittedly I'm not very familiar with `rioxaray` and `xarray` (only read about them but didn't use in daily work), and didn't have an incentive to learn it yet, because as far as I saw most topics discussed in the book could be achieved with `rasterio` (plus `rasterstats`, `richdem`, and `scipy` for specific purposes). I plan to learn `rioxarray` and `xarray` too as soon as I get the chance.

I think we need to focus on just one raster-ecosystem in the book, because discussing both data models will be too much information for the reader. So we need to pick one ecosystem that can solve as many of the use cases as possible, with the simplest code, and using as few as possible (stable) packages. The simple tasks (such as reading, writing, plotting, raster algebra, reclassify, crop, etc.) I imagine are easy in both ecosystems. So the question is, which ecosystem is better for the more complicated tasks: raster to points/polygons, extract to points/polygons, rasterizing vector layers, reprojecting/resampling. So far I saw that these other tasks are fairly more or less straightforward with `rasterio` (except perhaps for reprojecting/resampling), although much more low-level than what I'm used to in R. Would be interesting to compare how these are done with `rioxarray`! I believe we need to look at the big picture: what will be easier for the user to learn, if they need to be able to do all or as many as possible of the tasks in the book table of contents (such as above-mentioned), and going to learn just one ecosystem?

I had the impression (again, will be happy to learn from your more extensive experience) that `rioxarray` is more advantageous for working with data cubes, such those originating from NetCDF (aggregation in various ways, working with more than 3 dimensions, etc.), which the book doesn't cover, while having less support for "classic" GIS operations such as raster-vector interactions mentioned above. Also, I liked the fact that a `rasterio` raster is just a connection to read `numpy` arrays from along with spatial metadata, which feels more corresponding to the data model of simple rasters (GeoTIFF, etc.), although, again, I didn't like how low-level some of the operations can get (reprojection).

Overall, unfortunately, I had the impression that no Python raster ecosystem is quite comprehensive in the sense that, for instance, the `stars` package in R is, meaning that one can achieve all standard raster GIS tasks relying on a single package and using a single or few expression(s) while also being compatible with the vector data formats.

**Comment by michaeldorman** [comment]
Now that I think about it, even though it may be too much to explain both raster ecosystems in the printed book, but we can use an online supplement to do that. For example, we can include an online supplement introducing and demonstrating (some of) the raster examples from the book using `rioxarray` instead of `rasterio` (or vice versa).

**Comment by lwasser** [comment]
+1 to what @jsta wrote... I can tell you that i taught using rasterio for a few years. And when we switched to rioxarray / xarray the volume and complexity of cold decreased 10 fold. With rasterio you essentially have a numpy array and a meta object that you have to port around and update. rioxarray is an object and it has metadata embedded in that object such as .CRS, etc. it also supports things like reprojection which you'd have to manually compute with rasterio. totally doable but for anyone who is newer (and anyone really) it forced you to understand how reprojection == regridding, etc etc and it's just much more complex. even normal GIS operations dont' force you to know such things they handle the complex math. 

The other bonus is for anyone who plans to migrate to larger data in the future -remote sensing etc. whether it's multiple band or single band elevation data having things like lazy loading, etc just get you a lot further without crushing compute resources - especially if people are working through lessons locally vs cloud. under the hood rioxarray is using rasterio and xarray. so for us we made the switch after a few years and i'd never go back .it was a huge improvement on many levels.

The spatial data community in general here is catching up quickly. So even things like clip vector data. we had to write tools in earthpy to do that early on as it was SO MUCH CODE to teach. Eventually we gave those tools to geopandas where they belong. so i suggest sticking to tools that are simpler for people to use and have more expandability into the larger data realm which many if not people will need to do at some point. raster data get large fast.

**Comment by Nowosad** [comment]
Great discussion -- I am closing for now as we decided to stick with rasterio, but I am adding a label to be able to get back to this in the future.
